name: CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        go-version: ["1.25.3", "1.24.9"]
    runs-on: ubuntu-24.04
    services:
      db:
        image: mysql/mysql-server:8.0.28
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: |
          go test ./...
      - name: Check format
        run: |
          WRONG=$(go fmt)
          if [ -n "$WRONG" ]; then
            echo "Not formatted:"
            echo "$WRONG"
            exit 1
          fi
